"""Typed domain models for Open RCS solvers."""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


@dataclass(slots=True)
class AngleSweep:
    """Angular sweep definition for phi/theta observation cuts."""

    phi_start_deg: float
    phi_stop_deg: float
    phi_step_deg: float
    theta_start_deg: float
    theta_stop_deg: float
    theta_step_deg: float


@dataclass(slots=True)
class MaterialConfig:
    """Material-selection inputs for each simulation."""

    resistivity_mode: float
    material_path: str


@dataclass(slots=True)
class MonostaticSimulationConfig:
    """Monostatic solver configuration."""

    input_model: str
    frequency_hz: float
    correlation_distance_m: float
    standard_deviation_m: float
    incident_polarization: int
    angle_sweep: AngleSweep
    material: MaterialConfig
    use_numba: bool = True


@dataclass(slots=True)
class BistaticSimulationConfig:
    """Bistatic solver configuration."""

    input_model: str
    frequency_hz: float
    correlation_distance_m: float
    standard_deviation_m: float
    incident_polarization: int
    angle_sweep: AngleSweep
    incident_theta_deg: float
    incident_phi_deg: float
    material: MaterialConfig
    use_numba: bool = True


@dataclass(slots=True)
class GeometryData:
    """Prepared geometric model arrays used by the solvers."""

    x: np.ndarray
    y: np.ndarray
    z: np.ndarray
    x_points: np.ndarray
    y_points: np.ndarray
    z_points: np.ndarray
    n_vertices: int
    facet_numbers: np.ndarray
    node1: np.ndarray
    node2: np.ndarray
    node3: np.ndarray
    illumination_flag_mode: int
    illumination_flags: np.ndarray
    resistivity_values: np.ndarray
    n_triangles: int
    vertex_indices: np.ndarray
    vertex_coordinates: np.ndarray


@dataclass(slots=True)
class FieldAccumulator:
    """Running accumulation of scattering fields for one look direction."""

    theta_component: complex = 0.0 + 0.0j
    phi_component: complex = 0.0 + 0.0j
    diffuse_theta: float = 0.0
    diffuse_phi: float = 0.0


@dataclass(slots=True)
class SolverResult:
    """Output artifact paths generated by a simulation run."""

    plot_path: str
    figure_path: str
    data_path: str


@dataclass(slots=True)
class RcsComputationResult:
    """In-memory simulation outputs for plotting and analysis."""

    mode: str
    input_model: str
    wavelength_m: float
    phi_grid_deg: np.ndarray
    theta_grid_deg: np.ndarray
    rcs_theta_db: np.ndarray
    rcs_phi_db: np.ndarray
    direction_cosine_u_grid: np.ndarray
    direction_cosine_v_grid: np.ndarray
    direction_cosine_w_grid: np.ndarray
    geometry: GeometryData
